-- Flyway baseline generated by scripts/generate-flyway-baseline.sh
-- from the GORM domain model on 2026-08-19T14:27:28Z.
-- Regenerate instead of editing while the project is pre-beta.

CREATE TABLE public.ansible_repository (
    id bigint NOT NULL,
    version bigint NOT NULL,
    uuid character varying(255) NOT NULL,
    name character varying(190) NOT NULL,
    git_url character varying(1000) NOT NULL,
    branch character varying(190) NOT NULL,
    deploy_key_public text,
    deploy_key_private_enc text,
    sync_status character varying(255) NOT NULL,
    sync_error text,
    last_commit character varying(64),
    last_synced_at timestamp without time zone,
    date_created timestamp without time zone NOT NULL
);

CREATE TABLE public.app_user (
    id bigint NOT NULL,
    version bigint NOT NULL,
    uuid character varying(255) NOT NULL,
    username character varying(190) NOT NULL,
    password_hash character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    enabled boolean NOT NULL,
    source character varying(5) NOT NULL,
    all_groups boolean NOT NULL,
    date_created timestamp without time zone NOT NULL,
    last_updated timestamp without time zone NOT NULL
);

CREATE TABLE public.audit_log_entry (
    id bigint NOT NULL,
    version bigint NOT NULL,
    actor character varying(190) NOT NULL,
    action character varying(100) NOT NULL,
    entity_type character varying(60),
    entity_id character varying(190),
    summary character varying(1000),
    ip character varying(64),
    date_created timestamp without time zone NOT NULL
);

CREATE TABLE public.config_variable (
    id bigint NOT NULL,
    version bigint NOT NULL,
    device_group_id bigint,
    device_id bigint,
    name character varying(190) NOT NULL,
    value_json text NOT NULL,
    secret boolean NOT NULL,
    date_created timestamp without time zone NOT NULL,
    last_updated timestamp without time zone NOT NULL
);

CREATE TABLE public.device (
    id bigint NOT NULL,
    version bigint NOT NULL,
    uuid character varying(255) NOT NULL,
    hostname character varying(253) NOT NULL,
    agent_version character varying(100),
    token_hash character varying(255) NOT NULL,
    facts_json text,
    status character varying(255) NOT NULL,
    last_contact_at timestamp without time zone,
    last_ip character varying(64),
    last_job_at timestamp without time zone,
    offline_alerted_at timestamp without time zone,
    date_created timestamp without time zone NOT NULL
);

CREATE TABLE public.device_group (
    id bigint NOT NULL,
    version bigint NOT NULL,
    uuid character varying(255) NOT NULL,
    name character varying(190) NOT NULL,
    description character varying(1000),
    poll_interval_seconds integer,
    offline_alert_seconds integer,
    date_created timestamp without time zone NOT NULL
);

CREATE TABLE public.discovered_role (
    id bigint NOT NULL,
    version bigint NOT NULL,
    uuid character varying(255) NOT NULL,
    repository_id bigint NOT NULL,
    name character varying(190) NOT NULL,
    display_name character varying(190),
    description text,
    argument_spec_json text,
    defaults_json text,
    user_assignable boolean NOT NULL,
    base_role boolean NOT NULL,
    missing boolean NOT NULL,
    date_created timestamp without time zone NOT NULL,
    last_updated timestamp without time zone NOT NULL
);

CREATE TABLE public.enrollment_request (
    id bigint NOT NULL,
    version bigint NOT NULL,
    uuid character varying(255) NOT NULL,
    request_id character varying(128) NOT NULL,
    hostname character varying(255),
    facts_json text,
    status character varying(255) NOT NULL,
    date_created timestamp without time zone NOT NULL,
    last_seen_at timestamp without time zone,
    decided_by character varying(255),
    decided_at timestamp without time zone,
    device_id bigint
);

CREATE TABLE public.enrollment_token (
    id bigint NOT NULL,
    version bigint NOT NULL,
    uuid character varying(255) NOT NULL,
    label character varying(190) NOT NULL,
    token_hash character varying(255) NOT NULL,
    max_uses integer NOT NULL,
    used_count integer NOT NULL,
    expires_at timestamp without time zone,
    revoked boolean NOT NULL,
    created_by character varying(255),
    date_created timestamp without time zone NOT NULL
);

CREATE TABLE public.enrollment_token_device_group (
    enrollment_token_target_groups_id bigint NOT NULL,
    device_group_id bigint
);

CREATE TABLE public.group_membership (
    id bigint NOT NULL,
    version bigint NOT NULL,
    device_id bigint NOT NULL,
    device_group_id bigint NOT NULL,
    date_created timestamp without time zone NOT NULL
);

CREATE TABLE public.group_role_assignment (
    id bigint NOT NULL,
    version bigint NOT NULL,
    uuid character varying(255) NOT NULL,
    device_group_id bigint NOT NULL,
    role_id bigint NOT NULL,
    "position" integer NOT NULL,
    enabled boolean NOT NULL,
    date_created timestamp without time zone NOT NULL
);

CREATE SEQUENCE public.hibernate_sequence
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE public.job (
    id bigint NOT NULL,
    version bigint NOT NULL,
    uuid character varying(255) NOT NULL,
    device_id bigint NOT NULL,
    batch_id bigint,
    type character varying(255) NOT NULL,
    payload_json text,
    spec_hash character varying(255),
    status character varying(255) NOT NULL,
    attempt integer NOT NULL,
    exit_code integer,
    error text,
    triggered_by character varying(255),
    run_after timestamp without time zone,
    date_created timestamp without time zone NOT NULL,
    delivered_at timestamp without time zone,
    started_at timestamp without time zone,
    finished_at timestamp without time zone
);

CREATE TABLE public.job_batch (
    id bigint NOT NULL,
    version bigint NOT NULL,
    uuid character varying(255) NOT NULL,
    triggered_by character varying(255),
    device_group_id bigint,
    stage character varying(6),
    date_created timestamp without time zone NOT NULL
);

CREATE TABLE public.job_log_chunk (
    id bigint NOT NULL,
    version bigint NOT NULL,
    job_id bigint NOT NULL,
    seq integer NOT NULL,
    content text NOT NULL,
    date_created timestamp without time zone NOT NULL
);

CREATE TABLE public.notification_channel (
    id bigint NOT NULL,
    version bigint NOT NULL,
    uuid character varying(255) NOT NULL,
    name character varying(190) NOT NULL,
    type character varying(7) NOT NULL,
    target character varying(1000) NOT NULL,
    enabled boolean NOT NULL,
    date_created timestamp without time zone NOT NULL
);

CREATE TABLE public.remote_session (
    id bigint NOT NULL,
    version bigint NOT NULL,
    uuid character varying(255) NOT NULL,
    device_id bigint NOT NULL,
    requested_by character varying(255),
    status character varying(255) NOT NULL,
    date_created timestamp without time zone NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    agent_connected_at timestamp without time zone,
    viewer_connected_at timestamp without time zone,
    closed_at timestamp without time zone,
    close_reason character varying(255)
);

CREATE TABLE public.sso_group_mapping (
    id bigint NOT NULL,
    version bigint NOT NULL,
    uuid character varying(255) NOT NULL,
    idp_group character varying(190) NOT NULL,
    role character varying(255),
    device_group_id bigint,
    date_created timestamp without time zone NOT NULL
);

CREATE TABLE public.user_group_scope (
    id bigint NOT NULL,
    version bigint NOT NULL,
    user_id bigint NOT NULL,
    device_group_id bigint NOT NULL
);

ALTER TABLE ONLY public.ansible_repository
    ADD CONSTRAINT ansible_repository_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.audit_log_entry
    ADD CONSTRAINT audit_log_entry_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.config_variable
    ADD CONSTRAINT config_variable_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.device_group
    ADD CONSTRAINT device_group_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.device
    ADD CONSTRAINT device_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.discovered_role
    ADD CONSTRAINT discovered_role_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.enrollment_request
    ADD CONSTRAINT enrollment_request_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.enrollment_token
    ADD CONSTRAINT enrollment_token_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.group_membership
    ADD CONSTRAINT group_membership_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.group_role_assignment
    ADD CONSTRAINT group_role_assignment_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.job_batch
    ADD CONSTRAINT job_batch_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.job_log_chunk
    ADD CONSTRAINT job_log_chunk_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.job
    ADD CONSTRAINT job_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.notification_channel
    ADD CONSTRAINT notification_channel_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.remote_session
    ADD CONSTRAINT remote_session_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.sso_group_mapping
    ADD CONSTRAINT sso_group_mapping_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.discovered_role
    ADD CONSTRAINT uk38d4eb001eb5672836e5a74a516e UNIQUE (repository_id, name);

ALTER TABLE ONLY public.user_group_scope
    ADD CONSTRAINT uk3f5e67a4c397e828b7318cfe6089 UNIQUE (user_id, device_group_id);

ALTER TABLE ONLY public.group_role_assignment
    ADD CONSTRAINT uk464b13075123a49d9792f5b62b63 UNIQUE (device_group_id, role_id);

ALTER TABLE ONLY public.job_log_chunk
    ADD CONSTRAINT uk9473a2388f2ff217b982d9757c8f UNIQUE (job_id, seq);

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT uk_3k4cplvh82srueuttfkwnylq0 UNIQUE (username);

ALTER TABLE ONLY public.device_group
    ADD CONSTRAINT uk_57daukku5sknts4kmieb4neqa UNIQUE (uuid);

ALTER TABLE ONLY public.enrollment_token
    ADD CONSTRAINT uk_5hbyhp25qbjffc26rfkp1rbra UNIQUE (uuid);

ALTER TABLE ONLY public.job
    ADD CONSTRAINT uk_5r9b84nw5u8lbjhmnf6moof5t UNIQUE (uuid);

ALTER TABLE ONLY public.ansible_repository
    ADD CONSTRAINT uk_694vw7l3qy7fekxyr47938l6s UNIQUE (uuid);

ALTER TABLE ONLY public.enrollment_request
    ADD CONSTRAINT uk_6llq7r3x6hsq7k148ml8s3p52 UNIQUE (uuid);

ALTER TABLE ONLY public.job_batch
    ADD CONSTRAINT uk_79d70uiu9c8xhnriwea9hjs2d UNIQUE (uuid);

ALTER TABLE ONLY public.discovered_role
    ADD CONSTRAINT uk_87tqcm2gu3x2c9ypcyh6eyrwn UNIQUE (uuid);

ALTER TABLE ONLY public.notification_channel
    ADD CONSTRAINT uk_dliu2brlvfukutui7k7ejpgds UNIQUE (name);

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT uk_fl8f83s53808r6xtilfaglkb UNIQUE (uuid);

ALTER TABLE ONLY public.notification_channel
    ADD CONSTRAINT uk_i32uddt53hkmlse27h7xokwcn UNIQUE (uuid);

ALTER TABLE ONLY public.enrollment_token
    ADD CONSTRAINT uk_j3qp4ynx5g3hk00ll97kqwwg2 UNIQUE (token_hash);

ALTER TABLE ONLY public.sso_group_mapping
    ADD CONSTRAINT uk_jqnvta8j0gho6yk8gs9we3wt8 UNIQUE (uuid);

ALTER TABLE ONLY public.device
    ADD CONSTRAINT uk_lcsquslb3ig7l6wsbwijoet4a UNIQUE (uuid);

ALTER TABLE ONLY public.device_group
    ADD CONSTRAINT uk_mc0noy61qcu2jks8lkg8xdore UNIQUE (name);

ALTER TABLE ONLY public.remote_session
    ADD CONSTRAINT uk_oijdf0p146e1cqbjd55grdifb UNIQUE (uuid);

ALTER TABLE ONLY public.device
    ADD CONSTRAINT uk_pe9hscbk5cj2755revb6xcwjl UNIQUE (token_hash);

ALTER TABLE ONLY public.ansible_repository
    ADD CONSTRAINT uk_r944h2p3ug2ebf8wetffmrtix UNIQUE (name);

ALTER TABLE ONLY public.enrollment_request
    ADD CONSTRAINT uk_tblrrdfpc2390k7wb1e8o0l4l UNIQUE (request_id);

ALTER TABLE ONLY public.group_role_assignment
    ADD CONSTRAINT uk_tfb4cjvnaion63rss8qi809ff UNIQUE (uuid);

ALTER TABLE ONLY public.group_membership
    ADD CONSTRAINT ukfb2bcfb7215150163a292a93911f UNIQUE (device_group_id, device_id);

ALTER TABLE ONLY public.user_group_scope
    ADD CONSTRAINT user_group_scope_pkey PRIMARY KEY (id);

CREATE INDEX idx_audit_date_created ON public.audit_log_entry USING btree (date_created);

ALTER TABLE ONLY public.remote_session
    ADD CONSTRAINT fk2egssw3a6u6hm0nkjqm71c3ni FOREIGN KEY (device_id) REFERENCES public.device(id);

ALTER TABLE ONLY public.group_role_assignment
    ADD CONSTRAINT fk2tdds9xl4nuwdlxoy8ss4kamw FOREIGN KEY (role_id) REFERENCES public.discovered_role(id);

ALTER TABLE ONLY public.enrollment_token_device_group
    ADD CONSTRAINT fk3n13aba9b60lyefuqnnnh4dte FOREIGN KEY (device_group_id) REFERENCES public.device_group(id);

ALTER TABLE ONLY public.enrollment_token_device_group
    ADD CONSTRAINT fk4q41afhfgct15955skdkujyoa FOREIGN KEY (enrollment_token_target_groups_id) REFERENCES public.enrollment_token(id);

ALTER TABLE ONLY public.enrollment_request
    ADD CONSTRAINT fk838hx37qjjbys8d0earnosvoh FOREIGN KEY (device_id) REFERENCES public.device(id);

ALTER TABLE ONLY public.discovered_role
    ADD CONSTRAINT fk939s7awgd2ugf8tkkhqi9r43t FOREIGN KEY (repository_id) REFERENCES public.ansible_repository(id);

ALTER TABLE ONLY public.config_variable
    ADD CONSTRAINT fkb5an2anbptkuc4y29i040vu6y FOREIGN KEY (device_id) REFERENCES public.device(id);

ALTER TABLE ONLY public.job
    ADD CONSTRAINT fkb9ygn20vju9eu9pmrjxo3txwq FOREIGN KEY (device_id) REFERENCES public.device(id);

ALTER TABLE ONLY public.config_variable
    ADD CONSTRAINT fkcr666g36w2o579dfr5j8cexc4 FOREIGN KEY (device_group_id) REFERENCES public.device_group(id);

ALTER TABLE ONLY public.user_group_scope
    ADD CONSTRAINT fkd2fyldcq7d7jm1mdb79i01poa FOREIGN KEY (user_id) REFERENCES public.app_user(id);

ALTER TABLE ONLY public.sso_group_mapping
    ADD CONSTRAINT fkf364gyf8afw5vr4permrlwkkb FOREIGN KEY (device_group_id) REFERENCES public.device_group(id);

ALTER TABLE ONLY public.job_log_chunk
    ADD CONSTRAINT fkffd01353j128y7wp5m02bw90s FOREIGN KEY (job_id) REFERENCES public.job(id);

ALTER TABLE ONLY public.group_role_assignment
    ADD CONSTRAINT fkfp95ah0f1f97p0wiu8iakw8mh FOREIGN KEY (device_group_id) REFERENCES public.device_group(id);

ALTER TABLE ONLY public.group_membership
    ADD CONSTRAINT fki2v2whe535gn8benlfahxftn1 FOREIGN KEY (device_group_id) REFERENCES public.device_group(id);

ALTER TABLE ONLY public.user_group_scope
    ADD CONSTRAINT fkl1agi9vbqlulgnea9u3gefsfw FOREIGN KEY (device_group_id) REFERENCES public.device_group(id);

ALTER TABLE ONLY public.group_membership
    ADD CONSTRAINT fkqg5ku2gvnrp1o12gg41cgmet8 FOREIGN KEY (device_id) REFERENCES public.device(id);

ALTER TABLE ONLY public.job_batch
    ADD CONSTRAINT fkqq39sacf3iuxswrl4a73s9r0x FOREIGN KEY (device_group_id) REFERENCES public.device_group(id);

ALTER TABLE ONLY public.job
    ADD CONSTRAINT fkreuc2f9ugin2w79313go4qyu5 FOREIGN KEY (batch_id) REFERENCES public.job_batch(id);

