#!/usr/bin/env bash
# Regenerates the Flyway V1 baseline from the current GORM domain model.
#
# Boots the server once against a scratch PostgreSQL database with
# Hibernate DDL enabled (SVENAGER_DB_CREATE=update) and Flyway disabled,
# dumps the resulting schema and writes it to
# server/src/main/resources/db/migration/V1__baseline.sql.
#
# Requirements: the dev PostgreSQL container (default name: psql) is
# running, JAVA_HOME points to a JDK 17. Historical: the baseline is
# frozen at 0.9.0 — model changes since then ship as V<n> migrations in
# the same directory (V2__repository_auth.sql onwards), never as a
# regenerated baseline.
set -euo pipefail

CONTAINER="${SVENAGER_PG_CONTAINER:-psql}"
PGUSER="${SVENAGER_PG_USER:-svenager}"
PGADMIN="${SVENAGER_PG_ADMIN:-postgres}"
SCRATCH_DB="svenager_baseline_$$"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/server/src/main/resources/db/migration/V1__baseline.sql"
LOG="$(mktemp -t svenager-baseline)"

echo "==> creating scratch database $SCRATCH_DB"
docker exec "$CONTAINER" psql -U "$PGADMIN" -d postgres -q \
    -c "CREATE DATABASE $SCRATCH_DB OWNER $PGUSER"
cleanup() {
    # bootRun spawns a java child the subshell kill does not reach.
    lsof -ti :8080 2>/dev/null | xargs kill 2>/dev/null || true
    kill "$SERVER_PID" 2>/dev/null || true
    wait "$SERVER_PID" 2>/dev/null || true
    sleep 2
    docker exec "$CONTAINER" psql -U "$PGADMIN" -d postgres -q \
        -c "DROP DATABASE IF EXISTS $SCRATCH_DB WITH (FORCE)" || true
}
trap cleanup EXIT

echo "==> booting the server once with Hibernate DDL (log: $LOG)"
(
    cd "$ROOT/server"
    SVENAGER_DB_URL="jdbc:postgresql://localhost:5432/$SCRATCH_DB" \
    SVENAGER_DB_CREATE=update \
    SPRING_FLYWAY_ENABLED=false \
    ./gradlew bootRun --console=plain >"$LOG" 2>&1
) &
SERVER_PID=$!

for i in $(seq 1 120); do
    if curl -fs http://localhost:8080/actuator/health >/dev/null 2>&1; then
        break
    fi
    if ! kill -0 "$SERVER_PID" 2>/dev/null; then
        echo "server exited early — see $LOG" >&2
        exit 1
    fi
    sleep 2
done
curl -fs http://localhost:8080/actuator/health >/dev/null || {
    echo "server did not become healthy — see $LOG" >&2
    exit 1
}

echo "==> dumping schema"
mkdir -p "$(dirname "$OUT")"
{
    echo "-- Flyway baseline generated by scripts/generate-flyway-baseline.sh"
    echo "-- from the GORM domain model on $(date -u +%Y-%m-%dT%H:%M:%SZ)."
    echo "-- Regenerate instead of editing while the project is pre-beta."
    docker exec "$CONTAINER" pg_dump -U "$PGUSER" --schema-only \
        --no-owner --no-privileges "$SCRATCH_DB" \
        | grep -vE '^(--|SET |SELECT pg_catalog)' \
        | cat -s
} > "$OUT"

echo "==> wrote $OUT ($(grep -c 'CREATE TABLE' "$OUT") tables)"
