#!/bin/sh
# Prepares a Raspberry Pi (or any Debian) as a Svenager golden image that can
# be cloned for rollout. Every clone regenerates its identity on first
# boot and then asks the server for enrollment approval (Enrollment page).
#
# On the master device, as root:
#   ./pi-golden-image.sh --server https://svenager.example.org [options]
#
# Options:
#   --server URL          Svenager instance the devices report to (required
#                         unless --seal-only)
#   --hostname-prefix P   first boot names the device P-<serial> (default: pi)
#   --seal-only           skip install/download, just wipe identity again
#   --shutdown            power off after sealing so the card can be imaged
#
# Sealing removes: agent identity (/etc/svenager/agent.json + device-token),
# /etc/machine-id (regenerated by systemd on boot), SSH host keys, dhcpcd
# DUID/leases, and the first-boot marker. Re-run to re-seal after changes.
set -eu

SERVER=""
PREFIX="pi"
SEAL_ONLY=0
SHUTDOWN=0
while [ "$#" -gt 0 ]; do
  case "$1" in
    --server) SERVER="${2%/}"; shift 2 ;;
    --hostname-prefix) PREFIX="$2"; shift 2 ;;
    --seal-only) SEAL_ONLY=1; shift ;;
    --shutdown) SHUTDOWN=1; shift ;;
    -h|--help) sed -n '2,20p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "unknown option: $1" >&2; exit 2 ;;
  esac
done
[ "$(id -u)" = "0" ] || { echo "please run as root (sudo)" >&2; exit 1; }
if [ "$SEAL_ONLY" = "0" ] && [ -z "$SERVER" ]; then
  echo "usage: $0 --server <url> [--hostname-prefix pi] [--shutdown]" >&2; exit 2
fi

AGENT=/usr/local/bin/svenager-agent
CONF_DIR=/etc/svenager
MARKER=$CONF_DIR/firstboot-done

install_agent() {
  case "$(uname -m)" in
    x86_64)  ARCH=amd64 ;;
    aarch64) ARCH=arm64 ;;
    armv7l)  ARCH=armv7 ;;
    armv6l)  ARCH=armv6 ;;
    *) echo "unsupported architecture: $(uname -m)" >&2; exit 1 ;;
  esac

  if ! command -v ansible-playbook >/dev/null 2>&1 || ! command -v git >/dev/null 2>&1; then
    echo "Installing prerequisites (git, ansible-core) ..."
    export DEBIAN_FRONTEND=noninteractive
    apt-get update -qq
    apt-get install -y -qq --no-install-recommends git ansible-core \
      || apt-get install -y -qq --no-install-recommends git ansible
  fi

  echo "Downloading svenager-agent (linux-$ARCH) from $SERVER ..."
  curl -fsSL "$SERVER/install/agent/linux-$ARCH" -o "$AGENT.tmp"
  install -m 755 "$AGENT.tmp" "$AGENT"
  rm -f "$AGENT.tmp"
  mkdir -p "$CONF_DIR" /var/lib/svenager

  # First boot of a clone: fresh identity before anything announces itself.
  cat > /usr/local/sbin/svenager-firstboot <<FIRSTBOOT
#!/bin/sh
set -eu
PREFIX="$PREFIX"
MARKER="$MARKER"

serial=\$(tr -d '\\0' </sys/firmware/devicetree/base/serial-number 2>/dev/null \\
  || awk '/^Serial/ {print \$3}' /proc/cpuinfo 2>/dev/null || true)
[ -n "\$serial" ] || serial=\$(cat /sys/class/net/eth0/address /sys/class/net/wlan0/address \\
  /sys/class/net/end0/address 2>/dev/null | head -n1 | tr -d ':')
[ -n "\$serial" ] || serial=\$(cat /etc/machine-id)
name="\$PREFIX-\$(printf '%s' "\$serial" | tail -c 8 | tr 'A-F' 'a-f')"

old=\$(cat /etc/hostname 2>/dev/null || hostname)
echo "\$name" > /etc/hostname
hostname "\$name"
if grep -q "^127\\.0\\.1\\.1" /etc/hosts; then
  sed -i "s/^127\\.0\\.1\\.1.*/127.0.1.1\\t\$name/" /etc/hosts
else
  printf '127.0.1.1\\t%s\\n' "\$name" >> /etc/hosts
fi

ssh-keygen -A >/dev/null
rm -f $CONF_DIR/agent.json $CONF_DIR/device-token
date -u +%Y-%m-%dT%H:%M:%SZ > "\$MARKER"
echo "svenager-firstboot: \$old -> \$name, ssh host keys and identity regenerated"
FIRSTBOOT
  chmod 755 /usr/local/sbin/svenager-firstboot

  cat > /etc/systemd/system/svenager-firstboot.service <<UNIT
[Unit]
Description=Svenager first boot: regenerate cloned device identity
DefaultDependencies=no
ConditionPathExists=!$MARKER
After=local-fs.target
Before=network-pre.target ssh.service regenerate_ssh_host_keys.service svenager-agent.service
Wants=network-pre.target

[Service]
Type=oneshot
ExecStart=/usr/local/sbin/svenager-firstboot
RemainAfterExit=yes

[Install]
WantedBy=sysinit.target
UNIT

  # Same unit as install.sh, but token-less: waits for admin approval.
  cat > /etc/systemd/system/svenager-agent.service <<UNIT
[Unit]
Description=Svenager device agent
Documentation=https://github.com/klackwerk/svenager
After=network-online.target svenager-firstboot.service
Wants=network-online.target

[Service]
ExecStart=$AGENT run --server $SERVER
Restart=on-failure
RestartSec=10

[Install]
WantedBy=multi-user.target
UNIT

  systemctl daemon-reload
  systemctl enable svenager-firstboot.service svenager-agent.service
  echo "Installed $($AGENT version); agent registers against $SERVER on boot."
}

seal() {
  echo "Sealing image: removing device identity ..."
  systemctl stop svenager-agent.service 2>/dev/null || true
  rm -f "$CONF_DIR/agent.json" "$CONF_DIR/device-token" "$MARKER"
  rm -rf /var/lib/svenager/jobs /var/lib/svenager/repos 2>/dev/null || true

  # Empty machine-id: systemd generates a new one on the next boot.
  : > /etc/machine-id
  [ -L /var/lib/dbus/machine-id ] || rm -f /var/lib/dbus/machine-id

  rm -f /etc/ssh/ssh_host_*_key /etc/ssh/ssh_host_*_key.pub
  rm -f /var/lib/dhcpcd/duid /var/lib/dhcpcd/*.lease /etc/dhcpcd.duid \
        /var/lib/dhcp/*.leases /var/lib/NetworkManager/*.lease 2>/dev/null || true
  rm -f /root/.bash_history /home/*/.bash_history 2>/dev/null || true
  journalctl --rotate --vacuum-time=1s >/dev/null 2>&1 || true
  echo "Sealed. Do NOT reboot before imaging — power off and copy the SD card."
}

[ "$SEAL_ONLY" = "1" ] || install_agent
seal

if [ "$SHUTDOWN" = "1" ]; then
  echo "Powering off in 5 seconds ..."
  sleep 5
  systemctl poweroff
else
  echo "Run 'sudo poweroff' now, then image the card (e.g. with dd or rpi-imager)."
fi
